upstream default {
  server 127.0.0.1:9000;
}

server { 
    # 指定监听端口
    listen 80;
    listen [::]:80;
    # 指定编码
    charset utf-8;
    # 域名
    server_name clash.seklure.com;
    # 开启SSL
    include /ssl/seklure.com/seklure.com.conf;
    # 启用流量控制
    # 限制当前站点最大并发数
    # limit_conn perserver 200;
    # 限制单个IP访问最大并发数
    # limit_conn perip 20;
    # 限制每个请求的流量上限（单位：KB）
    # limit_rate 512k;
    # 关联缓存配置
    # include cache.conf;
    # 关联php配置
    # include php.conf;
    # 开启rewrite
    # include /rewrite/default.conf;
    # 根目录
    # root /www;
    # 站点索引设置
    # index forum.php index.html index.htm default.php default.htm default.html index.php;
    # 日志
    access_log logs/default.log combined;
    error_log logs/default.log error;
    # 路由
    location ^~ / {
             # 文件目录
             root  /www;
             # 站点索引设置
             index forum.php index.html index.htm default.php default.htm default.html index.php;
             # 开启websocket
             # include websocket.conf;
             # 日志
             access_log logs/seklure.log combined;
             error_log logs/seklure.log error;
    }
    location ^~ /clash {
            # 开启websocket
            # include websocket.conf;
            client_max_body_size 100M;
			# 反向代理
            proxy_pass http://default;
            # 日志
            access_log logs/clash.log combined;
            error_log logs/clash.log error;
    }
    # 所有静态文件由nginx直接读
    location ~ .*.(htm|html|gif|jpg|jpeg|png|bmp|swf|ioc|rar|zip|txt|flv|mid|doc|ppt|pdf|xls|mp3|wma|gz|svg|mp4|ogg|ogv|webm|htc|xml|woff)$
    # 图片缓存时间设置
    {
       expires 1m;
    }
    # JS和CSS缓存时间设置
    location ~ .*.(js|css)?$
    {
       expires 1m;
    }
		
    location ~ /\.
    {
       deny all;
    }
}
